### ISSUE TITLE
content of popover will not inherit events and sometimes causes issues

### ISSUE THREAD

**Issue by helrac** [ciena-frost/ember-frost-popover#62]
The main issue here is there was an icon with a popover for mouseenter/leave. When it pops up, the content was right underneath the icon.

This allowed a user to slide their mouse into that content area which it has now left the origin from where the popover came. At this point it's in a weird state (mainly due to toggling) where it's now inverted and you need to go over this icon to close it. Effectively the page needs to be reloaded because this becomes unusable.

**Comment by juwara0** [comment]
Do you have some screenshots or animated content so we can better understand what it is that you are experiencing.
